name: ydits_ssc
description: "Saitama Sora Cam 用に制作された防災情報アプリケーション。"
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  logging: ^1.3.0
  flutter:
    sdk: flutter
  desktop_multi_window: ^0.2.1
  window_manager: ^0.5.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  configure:
    path: ./packages/configure
  version:
    path: ./packages/version
  http: ^1.2.2
  weather: ^3.1.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_secure_storage: ^4.2.1
  flutter_single_instance: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true
  fonts:
    - family: M PLUS 2
      fonts:
        - asset: ./fonts/MPLUS2-Medium.ttf
          weight: 500
        - asset: ./fonts/MPLUS2-Bold.ttf
          weight: 700
