name: ydits_ssc
description: "Saitama Sora Cam 用に制作された防災情報アプリケーション。"
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  desktop_multi_window: ^0.3.0
  window_manager: ^0.5.1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  configure:
    path: ./packages/configure
  version:
    path: ./packages/version
  http: ^1.6.0
  weather: ^3.2.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_secure_storage: ^9.2.4
  flutter_single_instance: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  custom_lint: ^0.8.1

flutter:
  uses-material-design: true
  fonts:
    - family: M PLUS 2
      fonts:
        - asset: ./fonts/MPLUS2-Medium.ttf
          weight: 500
        - asset: ./fonts/MPLUS2-Bold.ttf
          weight: 700
